server:
  port: 8081
spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/jmq-estudiante
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver